\."#############################################################################
\."$Id: cerebro_errnum.3,v 1.3 2005-06-01 16:40:23 achu Exp $
\."#############################################################################
.TH CEREBRO_ERRNUM 3 "May 2005" "LLNL" "LIBCEREBRO"
.SH "NAME"
cerebro_errnum, cerebro_strerror, cerebro_errormsg, cerebro_perror \-
cerebro error routines
.SH "SYNOPSIS"
.B #include <cerebro.h>
.sp
.BI "int cerebro_errnum(cerebro_t handle);"
.sp
.BI "int cerebro_nodelist_errnum(cerebro_nodelist_t nodelist);"
.sp
.BI "int cerebro_nodelist_iterator_errnum(cerebro_nodelist_iterator_t handle);"
.sp
.BI "char *cerebro_strerror(int errnum);"
.br
.SH "DESCRIPTION"
\fBcerebro_errnum()\fR returns the error code stored in the cerebro_t
handle passed in.

\fBcerebro_nodelist_errnum()\fR returns the error code stored in the cerebro_nodelist_t
nodelist passed in.

\fBcerebro_nodelist_iterator_errnum()\fR returns the error code stored in the cerebro_nodelist_iterator_t
nodelist passed in.

\fBcerebro_strerror()\fR returns a pointer to a string describing the
error code \fIerrnum\fR.

Generally, an error code is retrieved by
\fBcerebro_errnum()\fR, \fBcerebro_nodelist_errnum()\fR, or
\fBcerebro_nodelist_iterator_errnum()
and then passed to 
\fBcerebro_strerror()\fR.

.br
.SH "FILES"
/usr/include/cerebro.h
