\."#############################################################################
\."$Id: cerebro_strerror.3,v 1.1 2005-05-05 00:26:19 achu Exp $
\."#############################################################################
.TH CEREBRO_STRERROR 3 "May 2005" "LLNL" "LIBCEREBRO"
.SH "NAME"
cerebro_strerror \- retrieve cerebro error string
.SH "SYNOPSIS"
.B #include <cerebro.h>
.sp
.BI "char *cerebro_strerror(int errnum);"
.br
.SH "DESCRIPTION"
\fBcerebro_strerror()\fR returns a pointer to a string describing the
error code \fIerrnum\fR.  Generally, the error code is retrieved
by 
.BR cerebro_errnum(3).
.br
.SH "FILES"
/usr/include/cerebro.h
.SH "SEE ALSO"
cerebro_errnum(3), cerebro_errormsg(3), cerebro_perror(3)
