\."#############################################################################
\."$Id: cerebro_errnum.3,v 1.4 2005-06-28 22:14:12 achu Exp $
\."#############################################################################
.TH CEREBRO_ERRNUM 3 "May 2005" "LLNL" "LIBCEREBRO"
.SH "NAME"
cerebro_errnum, cerebro_strerror, cerebro_errormsg, cerebro_perror \-
cerebro error routines
.SH "SYNOPSIS"
.B #include <cerebro.h>
.sp
.BI "int cerebro_errnum(cerebro_t handle);"
.sp
.BI "int cerebro_metriclist_errnum(cerebro_metriclist_t metriclist);"
.sp
.BI "int cerebro_metriclist_iterator_errnum(cerebro_metriclist_iterator_t handle);"
.sp
.BI "int cerebro_nodelist_errnum(cerebro_nodelist_t nodelist);"
.sp
.BI "int cerebro_nodelist_iterator_errnum(cerebro_nodelist_iterator_t handle);"
.sp
.BI "char *cerebro_strerror(int errnum);"
.br
.SH "DESCRIPTION"
\fBcerebro_errnum()\fR returns the error code stored in the cerebro_t
handle passed in.

\fBcerebro_metriclist_errnum()\fR returns the error code stored in the
cerebro_metriclist_t passed in.

\fBcerebro_metriclist_iterator_errnum()\fR returns the error code
stored in the cerebro_metriclist_iterator_t passed in.

\fBcerebro_nodelist_errnum()\fR returns the error code stored in the
cerebro_nodelist_t passed in.

\fBcerebro_nodelist_iterator_errnum()\fR returns the error code stored
in the cerebro_nodelist_iterator_t passed in.

\fBcerebro_strerror()\fR returns a pointer to a string describing the
error code \fIerrnum\fR.

Generally, an error code is retrieved by calling
\fBcerebro_errnum()\fR, 
\fBcerebro_metriclist_errnum()\fR,
\fBcerebro_metriclist_iterator_errnum()
\fBcerebro_nodelist_errnum()\fR, or
\fBcerebro_nodelist_iterator_errnum()
and then passed to 
\fBcerebro_strerror()\fR to retrieve a string describing the error.

.br
.SH "FILES"
/usr/include/cerebro.h
