\."#############################################################################
\."$Id: cerebro_get_metric_data.3,v 1.1 2005-06-01 16:40:23 achu Exp $
\."#############################################################################
.TH CEREBRO_GET_METRIC_DATA 3 "May 2005" "LLNL" "LIBCEREBRO"
.SH "NAME"
cerebro_get_metric_data \- retrieve cerebro metric data
.SH "SYNOPSIS"
.B #include <cerebro.h>
.sp
.BI "cerebro_nodelist_t cerebro_get_metric_data(cerebro_t handle, const char *metric_name);"
.br
.SH "DESCRIPTION"
\fBcerebro_get_metric_data()\fR retrieves metric data for the metric 
\fImetric_name\fR from
the 
.B cerebrod
metric server and returns it in a cerebro nodelist.

The default behavior of \fBcerebro_get_metric_data()\fR can be altered by
setting alternate defaults using
.B cerebro_set_hostname(3),
.B cerebro_set_port(3),
.B cerebro_set_timeout_len(3),
or
.B cerebro_set_flags(3).  It can also be altered using the the cerebro
configuration file.  See 
.BR cerebro.conf(5)
for information on how the default behavior of
\fBcerebro_get_metric_data\fR can be altered.

.br
.SH "RETURN VALUES"
On success, a cerebro nodelist is returned.  On error, NULL is
returned, and an error code is returned in \fIhandle\fR.  The error
code can be retrieved via
.BR cerebro_errnum(3)
, and a description of the error code can be retrieved via
.BR cerebro_strerror(3).  
.br
.SH "ERRORS"
.TP
.B CEREBRO_ERR_NULLHANDLE
The handle parameter is NULL.  The cerebro_t handle must be created
with
.BR cerebro_handle_create(3).
.TP
.B CEREBRO_ERR_MAGIC_NUMBER
\fIhandle\fR has an incorrect magic number.  \fIhandle\fR does not
point to a cerebro_t handle or \fIhandle\fR has already been
destroyed.
.TP
.B CEREBRO_ERR_PARAMETERS
Invalid parameter passed in.
.TP
.B CEREBRO_ERR_HOSTNAME
Invalid hostname specified.
.TP
.B CEREBRO_ERR_ADDRESS
Invalid network address specified.
.TP
.B CEREBRO_ERR_CONNECT
Error connecting to 
.B cerebrod
updown server.
.TP
.B CEREBRO_ERR_CONNECT_TIMEOUT
Timed out connecting to
.B cerebrod
updown server.
.TP
.B CEREBRO_ERR_PROTOCOL
Error during protocol communication.
.TP
.B CEREBRO_ERR_PROTOCOL_TIMEOUT
Timeout during protocol communication.
.TP
.B CEREBRO_ERR_VERSION_INCOMPATIBLE
Version incompatible with updown server.
.TP
.B CEREBRO_ERR_CONFIG_FILE
A config file error occurred.
.TP
.B CEREBRO_ERR_CONFIG_MODULE
A config module error occurred.
.TP
.B CEREBRO_ERR_CLUSTERLIST_MODULE
A clusterlist module error occurred.
.TP
.B CEREBRO_ERR_OUTMEM
Out of memory.
.TP
.B CEREBRO_ERR_INTERNAL
An internal system error occurred.
.br
.SH "FILES"
/usr/include/cerebro.h
.SH "SEE ALSO"
cerebro_handle_create(3), cerebro_errnum(3), cerebro_strerror(3),
cerebro_set_hostname(3), cerebro_set_port(3),
cerebro_set_timeout_len(3), cerebro_set_flags(3), cerebro.conf(5)
