#!/bgl/ion/bin/bash
# $Id: cerebrod-bgl-ion,v 1.3 2005-08-26 16:10:46 achu Exp $
#
                                                                                       
case "$1" in
    start)
        echo "Starting cerebrod"
        # achu: BG/L is F'ed up, we need this for some reason
        LD_LIBRARY_PATH=/bgl/ion-toolchain/gnu/build-powerpc-bgl-linux-gnu/tempglibc-3\.2-install/lib
        export LD_LIBRARY_PATH
        /bgl/ion/usr/sbin/cerebrod
        ;;
    stop)
        echo "Shutting down cerebrod"
        killall cerebrod
        ;;
    status)
        echo "Checking for cerebrod: "
        ps -elf | grep cerebrod | grep -v grep
        ;;
    *)
        echo "Usage: $0 {start|stop|status}"
        exit 1
        ;;
esac
