#!/bin/sh
# $Id: cerebrod-bgl-ion,v 1.1 2005-08-26 00:33:14 achu Exp $
#

case "$1" in
    start)
        echo "Starting cerebrod"
        # achu: BG/L is F'ed up, we need this for some reason
        LD_LIBRARY_PATH=/bgl/ion-toolchain/gnu/build-powerpc-bgl-linux-gnu/tempglibc-3.2-install/lib
        export LD_LIBRARY_PATH
        /bgl/ion/usr/sbin/cerebrod
        ;;
    stop)
        echo "Shutting down cerebrod"
        pkill cerebrod
        ;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
        ;;
esac
